pets/urls.py
from django.urls import path
from .views import switchActivoMascota, camaraUpdate, camaraDetail, del_anotacion, serviceEdit, ServicioDelete, mascotaDetail, detailVeterinarias, listVeterinarias, listPet, add_anotacion, MascotaCreate, listServices, ServicioCreate, listCamara, CamaraCreate, MascotaUpdate, serviceDetail

urlpatterns = [
    path('mascotas/', listPet.as_view(), name='pet_list'),
    path('mascotas/add/', MascotaCreate.as_view(), name='pet_add'),
    path('mascotas/<int:pk>/', mascotaDetail.as_view(), name='mascota_detail'),
    path('mascotas/<int:mascotaId>/edit/', MascotaUpdate.as_view(), name='mascota_update'),
    path('mascotas/<int:pk>/switch/', switchActivoMascota, name='mascota_s_activo'),
    path('anotacion/del/<int:anotacionId>/', del_anotacion, name='anotacion_del'),
    path('anotacion/add/<int:mascotaId>/', add_anotacion, name='anotacion_add'),
    path('servicios/', listServices.as_view(), name='servicios_list'),
    path('servicios/add/', ServicioCreate.as_view(), name='servicio_add'),
    path('servicios/<int:pk>/', serviceDetail.as_view(), name='service_detail'),
    path('servicios/<int:servicioId>/del/', ServicioDelete, name='service_del'),
    path('servicios/<int:pk>/edit/', serviceEdit.as_view(), name='service_edit'),
    path('camaras/', listCamara.as_view(), name='camara_list'),
    path('camaras/add/', CamaraCreate.as_view(), name='camara_add'),
    path('camaras/<int:pk>/', camaraDetail.as_view(), name='camara_detail'),
    path('camaras/<int:pk>/edit/', camaraUpdate.as_view(), name='camara_edit'),
    path('veterinarias/', listVeterinarias.as_view(), name='veterinarias_list'),
    path('veterinarias/<int:pk>/', detailVeterinarias.as_view(), name='veterinaria_detail'),
]

plataforma/urls.py
from django.contrib import admin
from django.urls import path, include
from profiles.urls import profiles_patterns
from pages.urls import pages_patterns
from .views import HomePageView

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name="home"),
    path('', include(profiles_patterns)),
    path('', include('pets.urls')),
    #Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('cuenta/', include('registration.urls')),
    path('blog/', include(pages_patterns)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pets/models.py
from django.db import models
from django.contrib.auth.models import User
from registration.models import Cliente, Veterinaria

#'1era letra del nombre en español','Nombre del animal en español'
ANIMAL_CHOICE = (
     ('m','Mamífero'),
     ('p','Pez'),
     ('b','Ave'), #brid
     ('a','Anfibios'),
     ('r','Reptil'),
     ('o','Otro'),
)

def custom_upload_to(instance, filename):
    old_instance = Mascota.objects.get(pk=instance.pk)
    old_instance.avatar.delete()
    return 'mascotas/' + filename

class Mascota(models.Model):
    dueno = models.ForeignKey(User, verbose_name="Dueño", related_name="get_pets", on_delete=models.PROTECT)
    nombre = models.CharField(verbose_name="Nombre", max_length=100)
    raza = models.CharField(verbose_name="Raza", max_length=50)
    fechaDeNacimiento = models.DateField(verbose_name="Fecha de nacimiento", blank=True, null=True)
    avatar = models.ImageField(verbose_name="Foto",upload_to=custom_upload_to, null=True, blank=True)
    observaciones = models.TextField(null=True, blank=True)
    activo = models.BooleanField(default=True, verbose_name="Perfil activo")
    tipo = models.CharField(max_length=1, choices= ANIMAL_CHOICE)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    #def save(self, *args, **kwargs):
    #    if not self.activo:
    #          self.activo = True
    #    super(Mascota, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-activo','id']

    def __str__(self):
        return str(self.id) + " " + self.nombre

class AnotacionMascota(models.Model):
    creador = models.ForeignKey(User, verbose_name="Creador anotacion", on_delete=models.PROTECT)
    texto = models.CharField(verbose_name="anotacion", max_length=400)
    mascota = models.ForeignKey(Mascota, related_name="get_anotaciones", verbose_name="Mascota", on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Anotacion mascota"
        verbose_name_plural = "Anotaciones mascotas"
        ordering = ['-id']

class TiposServicios(models.Model):
    nombre = models.CharField(verbose_name="Nombre", max_length=100)
    descripcion = models.TextField(null=True, blank=True)
    estado = models.BooleanField()

    class Meta:
        verbose_name = "Tipo de servicio"
        verbose_name_plural = "Tipos de servicios"
        ordering = ['-id']

    def __str__(self):
        return self.nombre 

class Camara(models.Model):
    nombre = models.CharField(verbose_name="Nombre", max_length=100)
    descripcion = models.TextField(null=True, blank=True)
    estado = models.BooleanField(default=True)
    ip = models.CharField(verbose_name="Camara", max_length=150)
    veterinaria = models.ForeignKey(Veterinaria, related_name="get_camaras", on_delete=models.PROTECT)
    ciclo = models.BooleanField(default=False, verbose_name="Url para foto, requiere ciclo")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    def __str__(self):
        return self.nombre  


class Servicios(models.Model):
    fechaInicio = models.DateTimeField(verbose_name="Fecha de inicio", blank=True, null=True)
    fechaFin = models.DateTimeField(verbose_name="Fecha final", blank=True, null=True)
    tipo = models.ForeignKey(TiposServicios, on_delete=models.PROTECT)
    camara = models.ForeignKey(Camara, on_delete=models.PROTECT, related_name='get_servicios')
    cliente = models.PositiveIntegerField(verbose_name="Cc dueño")
    mascota = models.ForeignKey(Mascota, related_name='get_servicios', verbose_name="Mascota", on_delete=models.PROTECT, blank=True, null=True)
    veterinaria = models.ForeignKey(Veterinaria, related_name='get_servicios', verbose_name="Veterinaria", on_delete=models.PROTECT)
    estado = models.BooleanField(default="True")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Servicio"
        verbose_name_plural = "Servicios"
        ordering = ['-created']

    def __str__(self):
        return "Vet: " + self.veterinaria.user.username + " Tipo: " + str(self.tipo) + " Fecha: " + str(self.fechaInicio) 

pets/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils.datastructures import MultiValueDictKeyError
from django.http import HttpResponseRedirect, JsonResponse, Http404
from datetime import datetime, date, timedelta

from .forms import MascotaAddOwner, ServicioAdd, CamaraAdd, ServicioUpdate

from plataforma.utils import get_rol, get_perfil
from registration.models import Cliente, Veterinaria
from .models import Mascota,AnotacionMascota, Servicios, TiposServicios, Camara

def add_anotacion(request, mascotaId):
    json_responder = {'created':False}
    if request.user.is_authenticated:
        contenido = request.GET.get('content', None)
        if contenido:
            anotacion = AnotacionMascota.objects.create(creador=request.user, texto=contenido, mascota=Mascota.objects.get(id=mascotaId))
            json_responder['created'] = True
    else:
        raise Http404("El usuario no esta autenticado")
    return JsonResponse(json_responder)

def del_anotacion(request, anotacionId):
    json_responder = {'delete':False}
    if request.user.is_authenticated:
        instance = AnotacionMascota.objects.get(id=anotacionId)
        if request.user == instance.creador:
            instance.delete()
            json_responder['delete'] = True
        else:
            raise Http404("No concuerda")
    else:
        raise Http404("El usuario no esta autenticado")
    return JsonResponse(json_responder)

def ServicioDelete(request, servicioId):
    if request.user.is_authenticated:
        instance = Servicios.objects.get(id=servicioId)
        if request.user.perfil_v == instance.veterinaria:
            instance.delete()
        else:
            raise Http404("No concuerda")
    else:
        raise Http404("El usuario no esta autenticado")
    return HttpResponseRedirect('/servicios/')

@login_required
def switchActivoMascota(request, pk):
    m = Mascota.objects.get(id=pk)
    if m in request.user.get_pets.all():
        new = not m.activo
        m.activo = new
        m.save()
    return HttpResponseRedirect('/mascotas/')

@method_decorator(login_required, name="dispatch")
class serviceEdit(UpdateView):
    model = Servicios
    template_name = 'pets/servicios_update_form.html'
    template_name_suffix = '_update_form'
    form_class = ServicioUpdate
    success_url = reverse_lazy('servicios_list')

    def get(self, request, *args, **kwargs):
        if request.user.perfil_v:
            servicio = get_object_or_404(Servicios, id=kwargs['pk'])
            if servicio in request.user.perfil_v.get_servicios.all():
                self.object = servicio
                return super(UpdateView, self).get(request, *args, **kwargs)
            else:
                return HttpResponseRedirect(reverse_lazy('servicios_list'))
        else:
            return HttpResponseRedirect(reverse_lazy('servicios_list'))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mascota = self.get_object().mascota
        context['tipos_servicios'] = TiposServicios.objects.all()
        context['camaras'] = Camara.objects.filter(veterinaria=self.request.user.perfil_v)
        if mascota:
            context['mascota'] = self.get_object().mascota.nombre
        else:
            context['mascota'] = ""
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            servicio = Servicios.objects.get(id=kwargs['pk'])
            if request.POST['fechaInicio'] != '':
                if Cliente.objects.filter(cc=request.POST['cliente']).exists(): #Si existe el cliente con esa CC
                    try:
                        m = Mascota.objects.get(id=request.POST['mascota']) #la mascota
                        encontrado = True
                    except MultiValueDictKeyError:
                        encontrado = False
                    c = Cliente.objects.get(cc=request.POST['cliente']) #el cliente
                    if m:
                        servicio.mascota = m
                    if m in c.user.get_pets.all() and encontrado: #Si la mascota pertenece a las mascotas del cliente
                        if Servicios.objects.filter(mascota=m).exists():
                            servicio.fechaInicio = request.POST['fechaInicio']
                            if request.POST['fechaFin'] != '':
                                servicio.fechaFin = request.POST['fechaFin']
                        else:
                            servicio.fechaInicio = request.POST['fechaInicio']
                            if request.POST['fechaFin'] != '':
                                servicio.fechaFin = request.POST['fechaFin']
                    else:
                        return HttpResponseRedirect('/servicios/?noM')
                else: 
                    servicio.fechaInicio = request.POST['fechaInicio']
                    if request.POST['fechaFin'] != '':
                        servicio.fechaFin = request.POST['fechaFin']
            print(request.POST['cliente'])
            servicio.cliente = request.POST['cliente']
            servicio.tipo = TiposServicios.objects.get(id=request.POST['tipo'])
            servicio.camara = Camara.objects.get(id=request.POST['camara'])
            servicio.save()
        else:
            print( (request, "Error"))
            return HttpResponseRedirect('/servicios/?error')
        return HttpResponseRedirect(reverse_lazy('servicios_list'))

@method_decorator(login_required, name="dispatch")
class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaAddOwner
    success_url = reverse_lazy('pet_list')

    def post(self, request, *args, **kwargs):
        #print(request.POST)
        form = self.form_class(request.POST)
        if form.is_valid():
            mascota = form.save(commit=False)
            mascota.dueno = request.user
            mascota.fechaDeNacimiento = request.POST['fechaDeNacimiento']
            mascota.save()
            return HttpResponseRedirect('/mascotas/?ok')
        return render(request, self.template_name, {'form': form})

@method_decorator(login_required, name="dispatch")
class MascotaUpdate(UpdateView):
    model = Mascota
    fields = ['nombre', 'avatar', 'raza', 'fechaDeNacimiento', 'tipo', 'observaciones']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('pet_list')

    def get(self, request, *args, **kwargs):
        mascota = get_object_or_404(Mascota, id=kwargs['mascotaId'])
        if mascota in request.user.get_pets.all():
            self.object = self.get_object()
            return super(UpdateView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect('/mascotas/')

    def get_object(self):
        mascota = get_object_or_404(Mascota, id=self.kwargs['mascotaId'])
        return mascota

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['servicios'] = Servicios.objects.filter(mascota=self.get_object())
        context['anotaciones'] = AnotacionMascota.objects.filter(mascota=self.get_object())
        context['mascotaId'] = self.kwargs['mascotaId']
        return context

@method_decorator(login_required, name="dispatch")
class mascotaDetail(DetailView):
    model = Mascota

@method_decorator(login_required, name="dispatch")
class ServicioCreate(CreateView):
    model = Servicios
    form_class = ServicioAdd
    success_url = reverse_lazy('servicios_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tipos_servicios'] = TiposServicios.objects.all()
        context['camaras'] = Camara.objects.filter(veterinaria=self.request.user.perfil_v)
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            servicio = form.save(commit=False)
            if request.POST['fechaInicio'] == '':
                return HttpResponseRedirect('/servicios/add/?noFI')
            if Cliente.objects.filter(cc=request.POST['cliente']).exists(): #Si existe el cliente con esa CC
                try:
                    m = Mascota.objects.get(id=request.POST['mascota']) #la mascota
                except MultiValueDictKeyError:
                    m = False
                c = Cliente.objects.get(cc=request.POST['cliente']) #el cliente
                
                if m:
                    servicio.mascota = m
                if m in c.user.get_pets.all() or not m: #Si la mascota pertenece a las mascotas del cliente
                    if Servicios.objects.filter(mascota=m).exists():
                        lastSer = Servicios.objects.filter(mascota=m).first()   #el ultimo servicio de la mascota
                        if lastSer.fechaFin:
                            fechaFin = datetime(lastSer.fechaFin.year, lastSer.fechaFin.month, lastSer.fechaFin.day, lastSer.fechaFin.hour, lastSer.fechaFin.minute)
                        else:
                            fechaFin =  lastSer.fechaInicio + timedelta(days=3)
                            fechaFin = datetime(fechaFin.year, fechaFin.month, fechaFin.day, fechaFin.hour, fechaFin.minute)
                        print(request.POST['fechaInicio'])
                        año = int(request.POST['fechaInicio'][:4])
                        mes = int(request.POST['fechaInicio'][5:7])
                        dia = int(request.POST['fechaInicio'][8:10])
                        hora = int(request.POST['fechaInicio'][11:13])

pets/templates/pets/camara_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Detalle camara{% endblock %}
{% block content %}
<div class="col-sm-4">
    <p><b>Nombre: </b>{{ camara.nombre }}</p>
{% if camara.descripcion %}
    <p><b>Descripción: </b>{{ camara.descripcion }}</p>
{% endif %}
{% if camara.ip %}
    <p><b>Ip: </b>{{ camara.ip }}</p>
{% endif %}
</div>
<div class="col-sm-1"></div>
<div class="col-sm-7">
    <iframe width="100%" height="400" src="{{camara.ip}}" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
    <img id="dynamicImage" src="{{camara.ip}}" class="img-fluid" alt="Video no disponile. Por favor recargar o contactar con el proveedor. *Display disponible para navegador Firefox y Safari.">
    <p><small>Livecamera para navegadores Safaria y Firefox.</small></p>
    <p><small>Si presentas algun problema prueba con recargar la pagina.</small></p>
    
</div>
{% endblock %}

pets/templates/pets/camara_update_form.html
{% extends 'base.html' %}
{% block title %}Editar camara - {{camara.nombre}}{% endblock %}
{% block content %}
<div class="col-md-10 col-md-offset-1">
<form method="post">{% csrf_token %}
        <div class="col-md-6">
            <p><label class="mylabel">Nombre</label></p>   
            <input type="text" name="nombre" class="form-control" value="{{camara.nombre}}" maxlength="100" required="" id="id_nombre">
        </div>
        <div class="col-md-6">
            <p><label class="mylabel">Descripción</label></p>   
            <input type="text" name="descripcion" class="form-control" value="{{camara.descripcion}}" id="id_descripcion">
        </div>
    <div class="text-center">
        <input class="btn btn-primary btn-block" type="submit" value="Guardar" />
    </div>
</form>
</div>
{% endblock %}

pets/templates/pets/list_camara.html
{% extends 'base.html' %}
{% block title %}{{title}}{% endblock %}
{% block content %}
    {% if rol == 'c' %}
        Error
    {% elif rol == 'v' %}
    <div class="table-responsive">
    <table class="table table-hover">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Descipción</th>
                    <th>Ip</th>
                    <th>Estado</th>
                    <th>Fecha de creación</th>
                </tr>
            </thead>
          {% for camara in camara_list %}
              <tbody>
                  <tr>
                      <td>{{ camara.nombre }}</td>
                      <td>{{ camara.descripcion }}</td>
                      <td>{{ camara.ip }}</td>
                      <td>{{ camara.estado }}</td>
                      <td>{{ camara.created }}</td>
                      <td><a href="{% url 'camara_detail' camara.id %}"><i class="fa fa-eye" aria-hidden="true"></i></a></td>
                      <td><a href="{% url 'camara_edit' camara.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></td>
                  </tr>
              </tbody>
          {% endfor %}
          </table>
         </div> 
          <!-- Menú de paginación -->
          {% if is_paginated %}
          <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
                <li class="page-item ">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                </li>
              {% endif %}
              {% for i in paginator.page_range %}
                <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                  <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
              {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-item ">
                  <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                </li>
              {% endif %}
            </ul>
          </nav>
          {% endif %}
          
          <a href="{% url 'camara_add' %}" class="plus-a"><i class="fa fa-plus-circle" aria-hidden="true"></i></a>
         
    {% endif %}
{% endblock %}

{% block Js %}
<script>
$(function() {
    $('#myModal').modal('toggle')
});
</script>
{% endblock %}

pets/templates/pets/list_pet_cliente.html
<div class="table-responsive">
<table class="table table-hover">
  <thead>
      <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>Raza</th>
          <th>Fecha nacimiento</th>
          <th>Observaciones</th>
      </tr>
  </thead>
  <tbody>
  {% for mascota in mascota_list %}
  
    <tr {% if not mascota.activo %} class="active" {% endif %}>
        <td>{{ mascota.id }}</td>
        <td>{{ mascota.nombre }}</td>
        <td>{{ mascota.raza }}</td>
        <td>{{ mascota.fechaDeNacimiento }}</td>
        <td>{{ mascota.observaciones|truncatechars:"200" }}</td>
        <td><a href="{% url 'mascota_detail' mascota.id %}"><i class="fa fa-address-card" aria-hidden="true"></i></a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
</div>
<!-- Menú de paginación -->
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">&laquo;</a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      <li class="page-item {% if page_obj.number == i %}active{% endif %}">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">&raquo;</a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}
<a href="{% url 'pet_add' %}" class="plus-a"><i class="fa fa-plus-circle" aria-hidden="true"></i></a>

pets/templates/pets/list_pet_pre.html
{% extends 'base.html' %}
{% block title %}{{title}}{% endblock %}
{% block content %}
    {% if rol == 'c' %}
        {% include  'pets/list_pet_cliente.html' %}
    {% elif rol == 'v' %}
        {% include  'pets/list_pet_vet.html' %}
    {% endif %}
{% endblock %}

{% block Js %}
<script>
$(function() {
    $('#myModal').modal('toggle')
});
</script>
{% endblock %}

pets/templates/pets/list_pet_vet.html
<div class="table-responsive">
<table class="table table-hover">
  <thead>
      <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>Cc dueño</th>
          <th>Raza</th>
          <th>Fecha nacimiento</th>
          <th>Observaciones</th>
          <th></th>
      </tr>
  </thead>
{% for mascota in mascota_list %}
    <tbody>
        <tr>
            <td>{{ mascota.id }}</td>
            <td>{{ mascota.nombre }}</td>
            <td>{{ mascota.dueno.perfil_c.cc }}</td>
            <td>{{ mascota.raza }}</td>
            <td>{{ mascota.fechaDeNacimiento }}</td>
            <td>{{ mascota.observaciones }}</td>
            <td><a href="{% url 'mascota_detail' mascota.id %}"><i class="fa fa-folder"></i></a></td>
        </tr>
    </tbody>
{% endfor %}
</table>
  </div>    
      <!-- Menú de paginación -->
      {% if is_paginated %}
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
            <li class="page-item ">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1">&laquo;</a>
            </li>
          {% endif %}
          {% for i in paginator.page_range %}
            <li class="page-item {% if page_obj.number == i %}active{% endif %}">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="page-item ">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1">&raquo;</a>
            </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

pets/templates/pets/mascota_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>.panel.panel-headline{display:none;}img#foto{border-radius: 1000px;}</style>
{% endblock %}
{% block contentNext %}
<div class="col-md-6 col-sm-12">
    <div id="msctDtl" class="col-sm-12 panel">
        <p style="padding: 0 25px;
    font-size: 20px;">Información General {% if not mascota.activo %} - <u> Perfil desactivado </u>{% endif %}</p>
        <ul class="nav navbar-nav navbar-right" style="    position: absolute;
        right: 0;
        top: 0;z-index:1000;">
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'mascota_update' mascota.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
    </li>
    </ul>
    <div class="col-md-6 col-sm-12">
    {% if mascota.avatar %}
        <p class="text-center">
            <img id="foto" src="{{mascota.avatar.url}}" height="200" class="mx-auto d-block img-rounded imagen"  style="max-width: 100%;">
        </p>
    {% else %}
        <p class="text-center">
            <img id="foto" src="{% static 'registration/img/no-avatar-pet.png' %}" height="150" class=" img-fluid img-rounded imagen">
        </p>
    {% endif %}
    </div>
    <div class="col-md-6 col-sm-12">
        <p  class=""><b>Nombre:</b>  {{mascota.nombre}}</p>
        <p  class=""><b>Dueño:</b>
        {% if mascota.dueno.first_name or mascota.dueno.last_name %}
            {{mascota.dueno.first_name}} {{mascota.dueno.last_name}}
        {% else %}
            {{mascota.dueno.username}}
        {% endif %}
        </p>
        <p class=""><b>Fecha de nacimiento:</b> {{mascota.fechaDeNacimiento}}</p>
        <p class=""><b>Raza: </b> {{mascota.raza}}</p>
        <p class=""><b>Tipo: </b> {{mascota.get_tipo_display}}</p>
        <p class=""><b>Observaciones: </b> {{mascota.observaciones}}</p>    
    </div>
    </div>
<div class="panel col-sm-12" style="padding-bottom:20px;">
<h3><b>Anotaciones:</b></h3>
    {% for anotacion in mascota.get_anotaciones.all %}
        {{ anotacion.texto}}
        <br>
    {% endfor %}
</div>
</div>
<div class="panel col-md-6 col-sm-12">
<h3><b>Historial de servicios:</b></h3>
{% for servicio in mascota.get_servicios.all %}
    <p>Fecha incio: {{servicio.fechaInicio}} - Fecha salida: {{servicio.fechaFin}}</p>
    <p>Tipo: {{servicio.tipo.nombre}}</p>
    <hr>
{% endfor %}
</div>
{% endblock %}
{% block Js %}
{% endblock %}